### ISSUE TITLE
parcel: Cannot resolve dependency '_process'

### ISSUE THREAD

**Issue by Boscop** [justinwoo/purescript-web-audio-player-demo#2]
When I try to use parcel like [this](https://github.com/justinwoo/purescript-web-audio-player-demo/blob/master/package.json#L10) I get this error: https://github.com/parcel-bundler/parcel/issues/725

But it used to work before, and my app.js was smaller after the parcel step..

Any idea why it's not working anymore, or how to get it working again?

**Comment by justinwoo** [comment]
Don't think I ever got this to reproduce, but I run into random issues with Parcel in any case.
