### ISSUE TITLE
Repeat mode in iOS/Android Browsers

### ISSUE THREAD

**Issue by aareeph** [justinwoo/purescript-web-audio-player-demo#3]
Impressive work! This is actually not an issue but a question.

I have a question about iOS/Android browsers that they have limitation to loop the audio without user interaction. Let's say when the app goes to background or user has locked the device then is there a way to loop the audio?

Thanks!

**Comment by justinwoo** [comment]
Just looping a single track? Seems like there should be something we can use with Web Audio but no idea...

**Comment by aareeph** [comment]
Thanks for your reply. Yes looping a single track just like a seamless background music. When I try to use Web Audio sound stops when Safari is put in background or device is locked.

**Comment by justinwoo** [comment]
Huh, on Android it lets you continue playing a track while the browser is in the background and when you lock the phone.

**Comment by justinwoo** [comment]
Closing since I haven't found anything to do with this.
