### ISSUE TITLE
Failing build

### ISSUE THREAD

**Issue by buggymcbugfix** [justinwoo/purescript-web-audio-player-demo#4]
```
$ psc-package install
...
$ pulp --psc-package browserify --to dist
...
* Build successful.
* Browserifying...
* ERROR: EISDIR: illegal operation on a directory, rename './.dist' -> 'dist'
```
Any ideas on what I did wrong?

**Comment by justinwoo** [comment]
pretty sure pulp --to takes a filename, not a directory

https://github.com/justinwoo/purescript-web-audio-player-demo/blob/6f6b692ea83e840d39b32f2bd7db4a7965f44ca7/package.json#L10

**Comment by buggymcbugfix** [comment]
Whoops.

Works perfectly now! Thanks.
